---
title: "final"
format: pdf
---

Setup chunk:

```{r}
library(tidyverse)
library(dplyr)
library(janitor)
```

# Problem 1 

1a. 

He most likely used a logistic regression because they were testing whether the distant to water edge predicted for the probability of microhabitat use. In the second part, he most likely perform a chi square test of independence because they were testing whether bird species and habitat (which are categorical variables) were related. 

1b. 

Part A: 

The American Avocets were more or less likely to use a microhabitat depending on their distance from the water. Distance to water's edge is a significant factor that influences microhabitat use. 

Part B: 

Use of habitat showed to be different across Avocets, Forster's Terns, and Black-necked Stilts. The three species showed unique patterns in the use of managed ponds, marshes, salt ponds, and mudflats. 

1c. 

An additional variable that could contribute to the probability of Avocet microhabitat use is human activity. Maybe it could be measured as a categorical variable organized in low, medium, and high levels, assessed by how many people are present in the habitat hourly. The birds may avoid those areas with more human activity because it might affect how much the birds go out of their shelters/nests to go eat, or may trigger them to fly out of their habitat when people are really close to them. 

# Problem 2



